name: CI

on:
  push:
    # Publish `main` as container `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  CONTAINER_IMAGE_NAME: ${{ github.repository }}
  CONTAINER_IMAGE_REGISTRY: ghcr.io

jobs:
  # Publish image
  build:

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dir: 7.3
            version: 7.3
            latest: false
          - dir: 7.3/laravel
            version: 7.3-laravel
            latest: false
          - dir: 7.4
            version: 7.4
            latest: true
          - dir: 7.4/laravel
            version: 7.4-laravel
            latest: false

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        if: github.event_name == 'pull_request'
        run: |
          if [ -f ./${{ matrix.dir }}/docker-compose.test.yml ]; then
            docker-compose --file ./${{ matrix.dir }}/docker-compose.test.yml build
            docker-compose --file ./${{ matrix.dir }}/docker-compose.test.yml run sut
          else
            docker build . --file ./${{ matrix.dir }}
          fi

      - name: Build container image
        run: |
          buildah bud -f ./${{ matrix.dir }} --format=docker \
            --label org.opencontainers.image.title="$CONTAINER_IMAGE_NAME" \
            --label org.opencontainers.image.description="${{ github.event.repository.description }}" \
            --label org.opencontainers.image.url="${{ github.event.repository.html_url }}" \
            --label org.opencontainers.image.source="${{ github.event.repository.html_url }}" \
            --label org.opencontainers.image.version="${{ matrix.version }}" \
            --label org.opencontainers.image.created="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
            --label org.opencontainers.image.revision="${{ github.sha }}" \
            --label org.opencontainers.image.licenses="${{ github.event.repository.license.spdx_id }}" \
            --tag $CONTAINER_IMAGE_NAME .

      - name: Log in to GitHub Registry
        run: echo ${{ secrets.CR_PAT }} | buildah login -u ${{ github.actor }} --password-stdin $CONTAINER_IMAGE_REGISTRY

      - name: Push image to GitHub Registry
        if: github.event_name == 'push'
        run: |
          IMAGE_ID=$CONTAINER_IMAGE_REGISTRY/$CONTAINER_IMAGE_NAME

          if ${{ matrix.latest }}; then
            buildah tag $CONTAINER_IMAGE_NAME $IMAGE_ID:${{ matrix.version }} $IMAGE_ID:latest
            buildah push $IMAGE_ID:latest
          else
            buildah tag $CONTAINER_IMAGE_NAME $IMAGE_ID:${{ matrix.version }}
          fi

          buildah push $IMAGE_ID:${{ matrix.version }}

